### ISSUE TITLE
오탈자 제보합니다.

### ISSUE THREAD

**Issue by yenarue** [stepanowon/vuejs_book#4]
안녕하세요. 먼저, 좋은 책 출판해주셔서 감사드립니다.
덕분에 Vue.js를 빠르게 시작하고 있습니다!! :-D

p.122
options : 컴포넌트에서 렌더링할 **templet** 등을 지정합니다.
-> options : 컴포넌트에서 렌더링할 **template** 등을 지정합니다.

오탈자.md 파일에 없길래 제보합니다 :-)
Pull Request 할까 하다가 너무 간단한 오탈자라 Issues에 올려요~

확인 후 오탈자.md에 추가 부탁드립니다.

**Comment by stepanowon** [comment]
감사합니다.
내일 아침 출근해서 바로 수정하겠습니다

Android용 Outlook<https://aka.ms/ghei36> 다운로드

________________________________
